import type { MediaClip } from '../../shared/types';
import { useEditor } from '../state/editor';
import { constant, editable } from '../engine/timeline';
import { filterPresets, visualEffects } from '../engine/visualEffects';

export function VisualControls({ clip }: { clip: MediaClip }) {
  const state = useEditor(), project = state.project!, asset = project.media[clip.mediaId];
  if (asset.kind === 'audio') return null;
  const edit = (recipe: (clip: MediaClip) => void) => state.edit(project => recipe(editable(project, clip.id).clip as MediaClip));
  const number = (label: string, value: number, change: (value: number) => void, min = 0, max = 1, step = .05) => <label className="inspector-number">{label}<input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={event => { const value = Number(event.target.value); if (Number.isFinite(value) && value >= min && value <= max) change(value); }}/></label>;
  const color = (label: string, value: string, change: (value: string) => void) => <label className="inspector-number">{label}<input aria-label={label} type="color" value={value} onChange={event => change(event.target.value)}/></label>;
  return <div className="visual-controls"><details open><summary>Color & filters</summary>
    <label className="inspector-number">Filter preset<select aria-label="Filter preset" value={clip.filter?.preset ?? ''} onChange={event => edit(clip => { clip.filter = event.target.value ? { preset: event.target.value, intensity: clip.filter?.intensity ?? 1 } : undefined; })}><option value="">None</option>{filterPresets.map(name => <option key={name}>{name}</option>)}</select></label>
    {clip.filter && number('Filter intensity', clip.filter.intensity, value => edit(clip => { clip.filter!.intensity = value; }))}
    {(['brightness', 'contrast', 'saturation', 'temperature', 'vignette', 'sharpen'] as const).map(name => <div key={name}>{number(name[0].toUpperCase() + name.slice(1), clip.adjust[name], value => edit(clip => { clip.adjust[name] = value; }), ['vignette', 'sharpen'].includes(name) ? 0 : -1)}</div>)}
  </details><details><summary>Video effects</summary>
    {Object.entries(visualEffects).map(([type, label]) => {
      const effect = clip.effects.find(effect => effect.type === type);
      return <div key={type}><label className="check-row"><input aria-label={label} type="checkbox" checked={Boolean(effect?.enabled)} onChange={event => edit(clip => { const found = clip.effects.find(effect => effect.type === type); if (found) found.enabled = event.target.checked; else clip.effects.push({ type, enabled: event.target.checked, params: { amount: .5 } }); })}/>{label}</label>{effect?.enabled && type !== 'mirror' && number(`${label} strength`, Number(effect.params.amount), value => edit(clip => { clip.effects.find(effect => effect.type === type)!.params.amount = value; }))}</div>;
    })}
  </details><details><summary>Blend & mask</summary>
    <label className="inspector-number">Blend mode<select aria-label="Blend mode" value={clip.blendMode ?? 'normal'} onChange={event => edit(clip => { clip.blendMode = event.target.value as MediaClip['blendMode']; })}>{['normal', 'multiply', 'screen', 'overlay', 'add'].map(mode => <option key={mode}>{mode}</option>)}</select></label>
    <label className="inspector-number">Mask shape<select aria-label="Mask shape" value={clip.mask?.shape ?? ''} onChange={event => edit(clip => { clip.mask = event.target.value ? { shape: event.target.value as NonNullable<MediaClip['mask']>['shape'], x: .5, y: .5, width: .6, height: .6, rotation: 0, feather: .1, invert: false } : undefined; })}><option value="">None</option><option value="rectangle">Rectangle</option><option value="ellipse">Ellipse / circle</option><option value="linear">Linear</option></select></label>
    {clip.mask && <>{number('Mask X', clip.mask.x, value => edit(clip => { clip.mask!.x = value; }))}{number('Mask Y', clip.mask.y, value => edit(clip => { clip.mask!.y = value; }))}{number('Mask width', clip.mask.width, value => edit(clip => { clip.mask!.width = value; }), .01, 2)}{number('Mask height', clip.mask.height, value => edit(clip => { clip.mask!.height = value; }), .01, 2)}{number('Mask rotation', clip.mask.rotation, value => edit(clip => { clip.mask!.rotation = value; }), -360, 360, 1)}{number('Mask feather', clip.mask.feather, value => edit(clip => { clip.mask!.feather = value; }))}<label className="check-row"><input aria-label="Invert mask" type="checkbox" checked={clip.mask.invert} onChange={event => edit(clip => { clip.mask!.invert = event.target.checked; })}/>Invert mask</label></>}
  </details><details><summary>Chroma key</summary>
    <label className="check-row"><input aria-label="Enable chroma key" type="checkbox" checked={Boolean(clip.chromaKey)} onChange={event => edit(clip => { clip.chromaKey = event.target.checked ? { color: '#00ff00', similarity: .15, smoothness: .12, spill: .6 } : undefined; })}/>Remove key color</label>
    {clip.chromaKey && <>{color('Key color', clip.chromaKey.color, value => edit(clip => { clip.chromaKey!.color = value; }))}{number('Key similarity', clip.chromaKey.similarity, value => edit(clip => { clip.chromaKey!.similarity = value; }))}{number('Key smoothness', clip.chromaKey.smoothness, value => edit(clip => { clip.chromaKey!.smoothness = value; }))}{number('Spill suppression', clip.chromaKey.spill, value => edit(clip => { clip.chromaKey!.spill = value; }))}</>}
  </details><details><summary>Picture in picture</summary>
    <label className="inspector-number">Corner preset<select aria-label="Picture in picture preset" value="" onChange={event => { const corner = event.target.value; if (!corner) return; edit(clip => {
      const w = (asset.width ?? project.settings.width) * (1 - clip.crop.l - clip.crop.r), h = (asset.height ?? project.settings.height) * (1 - clip.crop.t - clip.crop.b);
      const fit = Math.min(project.settings.width / w, project.settings.height / h), halfW = w * fit / project.settings.width * .15, halfH = h * fit / project.settings.height * .15;
      clip.fit = 'fit'; clip.blurBackground = false; clip.transform.x = constant(corner.includes('left') ? .04 + halfW : .96 - halfW); clip.transform.y = constant(corner.includes('top') ? .04 + halfH : .96 - halfH); clip.transform.scale = constant(.3); clip.transform.rotation = constant(0);
      clip.frame = { radius: 80, borderWidth: 8, borderColor: '#ffffff', shadow: 35 };
    }); }}><option value="">Choose corner…</option>{['top-left', 'top-right', 'bottom-left', 'bottom-right'].map(name => <option key={name}>{name}</option>)}</select></label>
    <label className="check-row"><input aria-label="Enable clip frame" type="checkbox" checked={Boolean(clip.frame)} onChange={event => edit(clip => { clip.frame = event.target.checked ? { radius: 60, borderWidth: 8, borderColor: '#ffffff', shadow: 25 } : undefined; })}/>Rounded frame</label>
    {clip.frame && <>{number('Corner radius', clip.frame.radius, value => edit(clip => { clip.frame!.radius = value; }), 0, 500, 5)}{number('Border width', clip.frame.borderWidth, value => edit(clip => { clip.frame!.borderWidth = value; }), 0, 100, 1)}{color('Border color', clip.frame.borderColor, value => edit(clip => { clip.frame!.borderColor = value; }))}{number('Frame shadow', clip.frame.shadow, value => edit(clip => { clip.frame!.shadow = value; }), 0, 100, 1)}</>}
  </details><button className="secondary" onClick={() => edit(clip => { clip.adjust = { brightness: 0, contrast: 0, saturation: 0, temperature: 0, vignette: 0, sharpen: 0 }; delete clip.filter; delete clip.mask; delete clip.chromaKey; delete clip.frame; delete clip.blendMode; clip.effects = clip.effects.filter(effect => effect.type === 'flip'); })}>Reset visual effects</button></div>;
}
