import { test, expect, _electron as electron } from '@playwright/test';
import { resolve, join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { mkdir } from 'node:fs/promises';
import { captionClip } from '../../src/renderer/engine/captionImport';
import { makeMediaClip, makeTrack } from '../../src/renderer/engine/timeline';
import { runProcess } from '../../src/main/services/process';
import { ffmpegPath, ffprobePath } from '../../src/main/services/tools';

test('transcript cuts, stabilization, undo, persistence and exported audio/video', async () => {
  test.setTimeout(120000);
  const root = resolve('.test-data/m10-' + randomUUID()); await mkdir(root, { recursive: true });
  const source = join(root, 'source.mp4');
  await runProcess(ffmpegPath, ['-v', 'error', '-y', '-f', 'lavfi', '-i', 'testsrc2=size=320x240:rate=30:duration=4', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=4', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', source]);
  const app = await electron.launch({ executablePath: process.env.OPENCUT_EXECUTABLE, args: process.env.OPENCUT_EXECUTABLE ? [] : ['.'], env: { ...process.env, OPENCUT_TEST_DATA: join(root, 'app') } });
  try {
    const page = await app.firstWindow();
    await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, source);
    const project = await page.evaluate(async () => {
      const project = await window.opencut.projects.create('M10 acceptance', { width: 640, height: 480, fps: 30, sampleRate: 48000 });
      return window.opencut.media.pick(project.id);
    });
    const asset = Object.values(project.media)[0], video = makeTrack('video', 'video', 'Video'), captions = makeTrack('captions', 'text', 'Captions');
    video.clips = [makeMediaClip('video-clip', asset, video.id, 0)];
    captions.clips = [captionClip({ text: 'Keep remove this ending', start: 0, end: 4e6, words: ['Keep', 'remove', 'this', 'ending'].map((text, i) => ({ text, start: i * 1e6, end: (i + 1) * 1e6 })) }, captions.id, 'caption')];
    project.tracks = [video, captions];
    await page.evaluate(project => window.opencut.projects.saveEdit(project), project);
    await page.getByRole('button', { name: 'Open projects', exact: true }).click();
    await page.getByRole('button', { name: 'Open timeline', exact: true }).click();
    await page.getByRole('button', { name: 'Captions', exact: true }).click();
    await page.getByText('Edit video by transcript', { exact: true }).click();
    const words = page.getByRole('group', { name: 'Timed transcript words' });
    await words.getByRole('button', { name: 'remove', exact: true }).click();
    await words.getByRole('button', { name: 'this', exact: true }).click({ modifiers: ['Shift'] });
    await expect(page.getByText('2 words selected · 2.00 seconds to remove')).toBeVisible();
    await page.getByRole('button', { name: 'Delete selected words', exact: true }).click();
    await expect(words.getByRole('button')).toHaveCount(2);
    await page.getByRole('button', { name: 'Undo transcript edit', exact: true }).click();
    await expect(words.getByRole('button')).toHaveCount(4);
    await words.getByRole('button', { name: 'remove', exact: true }).click();
    await words.getByRole('button', { name: 'this', exact: true }).click({ modifiers: ['Shift'] });
    await page.getByRole('button', { name: 'Delete selected words', exact: true }).click();
    await page.screenshot({ path: 'test-results/transcript-editor.png', fullPage: true });
    await page.getByRole('button', { name: 'Close captions', exact: true }).click();
    await page.locator('[data-track-id="video"] .timeline-clip').first().click({ position: { x: 30, y: 30 } });
    await page.getByRole('button', { name: 'Stabilize video', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Stabilize video', exact: true })).toBeEnabled({ timeout: 30000 });
    await expect(page.getByRole('alert')).toHaveCount(0);
    await page.keyboard.press('Control+z');
    await expect(page.locator('[data-track-id="video"] .timeline-clip').first()).toContainText('source');
    await page.keyboard.press('Control+Shift+z');
    await expect(page.locator('[data-track-id="video"] .timeline-clip').first()).toContainText('stabilized-');
    await page.getByRole('button', { name: 'Source browser', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Media library' })).toBeVisible();
    const saved = await page.evaluate(async id => (await window.opencut.projects.open(id)).project, project.id);
    const clips = saved.tracks[0].clips;
    expect(clips).toMatchObject([{ start: 0, duration: 1e6, sourceIn: 0, sourceOut: 1e6 }, { start: 1e6, duration: 1e6, sourceIn: 3e6, sourceOut: 4e6 }]);
    expect(clips[0].type).toBe('media');
    if (clips[0].type !== 'media') throw new Error('Missing video');
    expect(clips[0].mediaId).not.toBe(asset.id); expect(saved.media[clips[0].mediaId].path).toContain('stabilized-');
    await page.getByRole('button', { name: 'Open timeline', exact: true }).click();
    const output = join(root, 'edited.mp4');
    await app.evaluate(({ dialog }, path) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: path }); }, output);
    await page.getByRole('button', { name: 'Export', exact: true }).click();
    await page.getByLabel('Resolution', { exact: true }).selectOption('480');
    await page.getByLabel('Encoder', { exact: true }).selectOption('software');
    await page.getByRole('button', { name: 'Export MP4', exact: true }).click();
    await expect(page.getByText('Export complete', { exact: true })).toBeVisible({ timeout: 60000 });
    const probe = JSON.parse(await runProcess(ffprobePath, ['-v', 'error', '-show_streams', '-show_format', '-of', 'json', output]));
    expect(Number(probe.format.duration)).toBeCloseTo(2, 1);
    expect(probe.streams.map((stream: { codec_type: string }) => stream.codec_type)).toEqual(['video', 'audio']);
  } finally { await app.evaluate(({ app }) => app.exit(0)).catch(() => {}); await app.close().catch(() => {}); }
});
